// benchmark: test_string_concat
import "../../std/time.zc"
import "../../std/string.zc"

fn main() {
    let iterations = 10000;
    let start = Time::now();

    let x = String::from("x");
    for (let i = 0; i < iterations; i = i + 1) {
        let _s = String::add(&x, &x);
    }

    let end = Time::now();
    let duration = end - start;
    printf("RESULT: %llu\n", duration);
    return 0;
}
